name: Build Node.js (Linux/ARM64)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: Automattic/vip-actions/expose-github-runtime@trunk
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 'lts/*'
      - run: sudo apt-get -qq update && sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - run: npm ci
      - run: node index.js
        env:
          BUILD_ARCH: arm64
