name: Build Node.js (Linux/ARM64)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 'lts/*'
      - run: sudo apt-get -qq update && sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - run: npm ci
      - run: node index.js
        env:
          BUILD_ARCH: arm64
