name: Build All

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_RUN_ID: ${{ github.run_id }}
  GITHUB_RETENTION_DAYS: ${{ github.retention_days}}
  GITHUB_SERVER_URL: ${{ github.server_url }}
  CXXFLAGS: -Os -g0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux-x64:
    name: Build Linux/x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: Automattic/vip-actions/expose-github-runtime@trunk
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: node index.js

  linux-arm64:
    name: Build Linux/arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: Automattic/vip-actions/expose-github-runtime@trunk
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 'lts/*'
      - run: sudo apt-get -qq update && sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - run: npm ci
      - run: node index.js
        env:
          BUILD_ARCH: arm64

  macos-x64:
    name: Build macOS/x64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: Automattic/vip-actions/expose-github-runtime@trunk
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 'lts/*'
      - run: npm ci
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: '3.10'
      - run: python -m pip install packaging
      - run: node index.js

  macos-arm64:
    name: Build macOS/arm64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: Automattic/vip-actions/expose-github-runtime@trunk
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 'lts/*'
      - run: npm ci
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: '3.10'
      - run: python -m pip install packaging
      - run: node index.js
        env:
          BUILD_ARCH: arm64

  windows-x64:
    name: Build Windows/x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: Automattic/vip-actions/expose-github-runtime@trunk
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 'lts/*'
      - run: npm ci
      - uses: ilammy/setup-nasm@13cbeb366c45c4379d3478cdcbadd8295feb5028 # v1.5.1
      - run: node index.js

  windows-x86:
    name: Build Windows/x86
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: Automattic/vip-actions/expose-github-runtime@trunk
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 'lts/*'
      - run: npm ci
      - uses: ilammy/setup-nasm@13cbeb366c45c4379d3478cdcbadd8295feb5028 # v1.5.1
      - run: node index.js
        env:
          BUILD_ARCH: x86
